Feature/mobile menu
Roathy/-Portfolio- pull request #5
Opened 2023-05-17 02:11 UTC by Roathy

In this branch I created the html for the navigation menu for the mobile version, add the styles to it and implement js for the event and display.

✅ No linters errors
✅ Navigation menu
✅ Click or tap on hamburger makes menu appear
✅ Click or tap on x makes menu disappear
✅ Click on option takes to that part of the website

2023-05-17 16:37 UTC, AdnanOlarmmi requested changes

2023-05-17 16:37 UTC, AdnanOlarmmi commented on scripts.js
- [ ] Kindly note that the requirement is that, the nav bar item is not visible on mobile screen but the hamburger menu button is not visible on desktop size, but it is visible on mobile devices. Upon clicking or tapping the hamburger button, the mobile menu will appear. To close the mobile menu, the user can click or tap the close (X) button. Selecting any option from the mobile menu will display the corresponding part of the page, and the mobile menu will disappear upon selecting an option. The design of the hamburger button and menu adheres to the chosen template in Figma, including elements such as font, colors, images, text, and margins.

- This is what your design currently looks like.
- ![mobile](https://github.com/Roathy/-Portfolio-/assets/41163571/da8c436c-3804-4c84-a735-6bbbe03d3ce6)

2023-05-17 16:42 UTC, AdnanOlarmmi requested changes

2023-05-17 16:42 UTC, AdnanOlarmmi commented on index.html
> +    </script>
- [ ] It's also not a good practice for you javascript code to be inside the HTML,

2023-05-26 00:22 UTC, emmanuellekamwa approved these changes
**STATUS: APPROVED 🍾✔🎉**
Hello @Roathy 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- Good commit messages.
- Descriptive PR.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-26 02:07 UTC, merged